// vocab-a-to-z.js
//
// Holds ONLY the "A to Z" vocabulary data: the full alphabetical list
// (VOCAB_A_TO_Z), imported from the master vocabulary spreadsheet. Unlike
// every other vocab-<name>.js file, this one is not split into named
// sub-category arrays plus a *_LISTS registry -- "A to Z" and its
// "Random (Casuale)" companion are both built directly from this single
// array by script.js (see startAtoZFull() / startRandomAtoZ()), because
// the A-to-Z mode plays through in the exact order below (never
// shuffled) and can also be filtered down to a single starting letter.
//
// Order matters here: the pairs below are grouped by first letter, in
// alphabetical order, exactly as arranged in the source spreadsheet.
// Do not reorder or re-sort this array -- script.js relies on this
// being the intended "A to Z" play order.
//
// To add/edit words: keep each entry as ["Italian", "English"], insert it
// under the correct letter block (matching the source spreadsheet), and
// bump this file's own "?v=N" wherever it's imported in script.js.
export const VOCAB_A_TO_Z = [
  // --- A ---
  ["A", "At / To"],
  ["Abitare", "To live"],
  ["Acqua", "Water"],
  ["Adesso", "Now"],
  ["Aeroplano", "Airplane"],
  ["Aeroporto", "Airport"],
  ["Ago", "Needle"],
  ["Aiuto", "Help"],
  ["Alba", "Dawn"],
  ["Albergo", "Hotel"],
  ["Albero", "Tree"],
  ["Albicocca", "Apricot"],
  ["Alto", "Tall"],
  ["Alunno", "Pupil"],
  ["Amico", "Friend"],
  ["Amore", "Love"],
  ["Ananas", "Pineapple"],
  ["Anatra", "Duck"],
  ["Anche", "Also"],
  ["Andare", "To go"],
  ["Anello", "Ring"],
  ["Animale", "Animal"],
  ["Aperto", "Open"],
  ["Appendere", "To hang"],
  ["Aquila", "Eagle"],
  ["Arancia", "Orange"],
  ["Arancione", "Orange"],
  ["Arcobaleno", "Rainbow"],
  ["Aria", "Air"],
  ["Aritmetica", "Arithmetic"],
  ["Armadio", "Cupboard"],
  ["Arrabbiato", "Angry"],
  ["Ascensore", "Lift"],
  ["Asciugamano", "Towel"],
  ["Asciutto", "Dry"],
  ["Ascoltare", "To listen"],
  ["Asino", "Donkey"],
  ["Aspettare", "To wait for"],
  ["Aspirapolvere", "Vacuum cleaner"],
  ["Assente", "Absent"],
  ["Astronauta", "Astronaut"],
  ["Astronave", "Spaceship"],
  ["Attraversare", "To cross"],
  ["Aula", "Classroom"],
  ["Autobus", "Bus"],
  ["Automobile", "Car"],
  ["Autostop", "Hitch hiking"],
  ["Autunno", "Autumn"],
  ["Avere", "To have"],
  // --- B ---
  ["Babbo Natale", "Father Christmas"],
  ["Bacio", "Kiss"],
  ["Bagnato", "Wet"],
  ["Balena", "Whale"],
  ["Ballare", "To dance"],
  ["Bambina", "Girl"],
  ["Bambini", "Children"],
  ["Bambino", "Boy"],
  ["Bambola", "Doll"],
  ["Banana", "Banana"],
  ["Banca", "Bank"],
  ["Banco", "Desk"],
  ["Bandiera", "Flag"],
  ["Barbiere", "Barber"],
  ["Barca", "Boat"],
  ["Basso", "Short"],
  ["Bastone", "Stick"],
  ["Bello", "Beautiful"],
  ["Bene", "Well"],
  ["Benzina", "Petrol"],
  ["Bere", "To drink"],
  ["Berretto", "Cap"],
  ["Bianco", "White"],
  ["Bicchiere", "Glass"],
  ["Bicicletta", "Bicycle"],
  ["Bilancia", "Scale"],
  ["Biondo", "Blond"],
  ["Biscotto", "Biscuit"],
  ["Bistecca", "Steak"],
  ["Blu", "Blue"],
  ["Bocca", "Mouth"],
  ["Borsa", "Bag"],
  ["Bosco", "Wood"],
  ["Bottiglia", "Bottle"],
  ["Bottone", "Button"],
  ["Braccio", "Arm"],
  ["Bruco", "Caterpillar"],
  ["Brutto", "Ugly"],
  ["Buco", "Hole"],
  ["Bugia", "Lie"],
  ["Buono", "Good"],
  ["Burro", "Butter"],
  ["Busta", "Envelope"],
  // --- C ---
  ["Cacciatore", "Hunter"],
  ["Caffè", "Coffee"],
  ["Calcio", "Soccer"],
  ["Caldo", "Hot"],
  ["Calza", "Sock"],
  ["Camello", "Camel"],
  ["Camicia", "Shirt"],
  ["Camion", "Lorry"],
  ["Camminare", "To walk"],
  ["Campagna", "Countryside"],
  ["Campanello", "Bell"],
  ["Campo da golf", "Golf course"],
  ["Campo da tennis", "Tennis court"],
  ["Cancello", "Gate"],
  ["Cane", "Dog"],
  ["Canguro", "Kangaroo"],
  ["Cantante", "Singer"],
  ["Capelli", "Hair"],
  ["Capello", "Hat"],
  ["Capire", "To understand"],
  ["Cappotto", "Coat"],
  ["Capra", "Goat"],
  ["Caramella", "Sweet"],
  ["Carne", "Meat"],
  ["Caro", "Dear"],
  ["Carota", "Carrot"],
  ["Carta", "Paper"],
  ["Cartoni animati", "Cartoons"],
  ["Casa", "Home"],
  ["Casco", "Helmet"],
  ["Cassaforte", "Safe"],
  ["Castagna", "Chestnut"],
  ["Castello", "Castle"],
  ["Castoro", "Beaver"],
  ["Cattivo", "Bad"],
  ["Cavalletta", "Grasshopper"],
  ["Cavallo", "Horse"],
  ["Cavolo", "Cabbage"],
  ["Cena", "Dinner"],
  ["Cerchio", "Circle"],
  ["Cervo", "Deer"],
  ["Che cos'è?", "What is it?"],
  ["Chi?", "Who?"],
  ["Chiamare", "To call"],
  ["Chiave", "Key"],
  ["Chiesa", "Church"],
  ["Chiodo", "Nail"],
  ["Chitarra", "Guitar"],
  ["Chiuso", "Closed"],
  ["Ciao", "Hello / Bye-bye"],
  ["Cielo", "Sky"],
  ["Cinema", "Cinema"],
  ["Cintura", "Belt"],
  ["Cioccolato", "Chocolate"],
  ["Cipolla", "Onion"],
  ["Circo", "Circus"],
  ["Città", "Town"],
  ["Coccinella", "Ladybird"],
  ["Coda", "Tail"],
  ["Colazione", "Breakfast"],
  ["Collana", "Necklace"],
  ["Collo", "Neck"],
  ["Coltello", "Knife"],
  ["Compleanno", "Birthday"],
  ["Comprare", "To buy"],
  ["Computer", "Computer"],
  ["Con", "With"],
  ["Conchiglia", "Shell"],
  ["Coniglio", "Rabbit"],
  ["Cono", "Cone"],
  ["Contadino", "Farmer"],
  ["Contare", "To count"],
  ["Contro", "Against"],
  ["Coperta", "Blanket"],
  ["Copiare", "To copy"],
  ["Coraggioso", "Brave"],
  ["Correre", "To run"],
  ["Corto", "Short"],
  ["Così", "So"],
  ["Cowboy", "Cowboy"],
  ["Cravatta", "Tie"],
  ["Cubo", "Cube"],
  ["Cucchiaio", "Spoon"],
  ["Cuoco", "Cook"],
  ["Cuore", "Heart"],
  // --- D ---
  ["Da", "From"],
  ["Dare", "To give"],
  ["Davanti a", "In front of"],
  ["Delfino", "Dolphin"],
  ["Dente", "Tooth"],
  ["Dentifricio", "Toothpaste"],
  ["Dentista", "Dentist"],
  ["Dentro", "In"],
  ["Destra", "Right"],
  ["Di", "Of"],
  ["Dietro", "Behind"],
  ["Difficile", "Difficult"],
  ["Dimenticare", "To forget"],
  ["Dinosauro", "Dinosaur"],
  ["Disegnare", "To draw"],
  ["Disordine", "Mess"],
  ["Dito", "Finger"],
  ["Divano", "Sofa"],
  ["Diverso", "Different"],
  ["Doccia", "Shower"],
  ["Domanda", "Question"],
  ["Domani", "Tomorrow"],
  ["Donna", "Woman"],
  ["Dormire", "To sleep"],
  ["Dottore", "Doctor"],
  ["Dove", "Where"],
  // --- E ---
  ["E", "And"],
  ["Eco", "Echo"],
  ["Educato", "Polite"],
  ["Elefante", "Elephant"],
  ["Elegante", "Elegant"],
  ["Elicottero", "Helicopter"],
  ["Entrata", "Entrance"],
  ["Erba", "Grass"],
  ["Errore", "Mistake"],
  ["Esame", "Exam"],
  ["Esercizio", "Exercise"],
  ["Esploratore", "Explorer"],
  ["Essere", "To be"],
  ["Estate", "Summer"],
  // --- F ---
  ["Fabbrica", "Factory"],
  ["Faccia", "Face"],
  ["Facile", "Easy"],
  ["Fagiolo", "Bean"],
  ["Fame (avere)", "To be hungry"],
  ["Fare", "To do"],
  ["Farfalla", "Butterfly"],
  ["Farmacia", "Chemist's"],
  ["Fata", "Fairy"],
  ["Fattoria", "Farm"],
  ["Favola", "Fable"],
  ["Fazzoletto", "Handkerchief"],
  ["Febbre", "Temperature"],
  ["Felice", "Happy"],
  ["Fermare", "To stop"],
  ["Ferroviere", "Railway worker"],
  ["Festa", "Party"],
  ["Fiammifero", "Match"],
  ["Figli", "Children"],
  ["Figlia", "Daughter"],
  ["Figlio", "Son"],
  ["Film", "Film"],
  ["Fine", "End"],
  ["Finestra", "Window"],
  ["Fiore", "Flower"],
  ["Fiume", "River"],
  ["Foca", "Seal"],
  ["Foglia", "Leaf"],
  ["Forbici", "Scissors"],
  ["Forchetta", "Fork"],
  ["Formaggio", "Cheese"],
  ["Formica", "Ant"],
  ["Forte", "Strong"],
  ["Fortunato", "Lucky"],
  ["Fotografia", "Photograph"],
  ["Fragola", "Strawberry"],
  ["Francobollo", "Stamp"],
  ["Fratello", "Brother"],
  ["Freddo", "Cold"],
  ["Frigorifero", "Fridge"],
  ["Frutta", "Fruit"],
  ["Fungo", "Mushroom"],
  ["Fuoco", "Fire"],
  ["Fuori", "Out"],
  // --- G ---
  ["Gabbiano", "Seagull"],
  ["Gallina", "Hen"],
  ["Gallo", "Cock"],
  ["Gamba", "Leg"],
  ["Gara", "Competition"],
  ["Garage", "Garage"],
  ["Gatto", "Cat"],
  ["Gelato", "Ice Cream"],
  ["Gemelli", "Twins"],
  ["Genitori", "Parents"],
  ["Gentile", "Kind"],
  ["Ghiaccio", "Ice"],
  ["Giacca", "Jacket"],
  ["Giallo", "Yellow"],
  ["Giardino", "Garden"],
  ["Ginnastica", "Gymnastics"],
  ["Giocare", "To play"],
  ["Giocattolo", "Toy"],
  ["Giornale", "Newspaper"],
  ["Giorno", "Day"],
  ["Giovane", "Young"],
  ["Giraffa", "Giraffe"],
  ["Giù", "Down"],
  ["Giudice", "Judge"],
  ["Gomma", "Rubber"],
  ["Gonna", "Skirt"],
  ["Gorilla", "Gorilla"],
  ["Grande", "Big"],
  ["Grano", "Corn"],
  ["Grasso", "Fat"],
  ["Grattacielo", "Skyscraper"],
  ["Grazie", "Thank you"],
  ["Gridare", "To shout"],
  ["Gru", "Crane"],
  ["Guanto", "Glove"],
  ["Guardare", "To look at"],
  ["Guidare", "To drive"],
  // --- I ---
  ["Idea", "Idea"],
  ["Ieri", "Yesterday"],
  ["Il, Lo, La, I, Gli, Le", "The"],
  ["Imbuto", "Funnel"],
  ["Imparare", "To learn"],
  ["Impermeabile", "Raincoat"],
  ["Importante", "Important"],
  ["Incendio", "Fire"],
  ["Indiano", "Indian"],
  ["Indicare", "To point to"],
  ["Indirizzo", "Address"],
  ["Infermiera", "Nurse"],
  ["Influenza", "Flu"],
  ["Informazione", "Information"],
  ["Inguinamento", "Pollution"],
  ["Insalata", "Salad"],
  ["Insieme", "Together"],
  ["Intelligente", "Clever"],
  ["Inverno", "Winter"],
  ["Ippopotamo", "Hippopotamus"],
  ["Isola", "Island"],
  // --- L ---
  ["Là", "There"],
  ["Lago", "Lake"],
  ["Lampada", "Lamp"],
  ["Lana", "Wool"],
  ["Latte", "Milk"],
  ["Lattina", "Can"],
  ["Lavare", "To wash"],
  ["Lavatrice", "Washing machine"],
  ["Lavorare", "To work"],
  ["Leggere", "To read"],
  ["Leggero", "Light (weight)"],
  ["Legno", "Wood"],
  ["Lento", "Slow"],
  ["Leone", "Lion"],
  ["Lepre", "Hare"],
  ["Lettera", "Letter"],
  ["Letto", "Bed"],
  ["Lezione", "Lesson"],
  ["Libro", "Book"],
  ["Limone", "Lemon"],
  ["Lingua", "Tongue / Language"],
  ["Lontano", "Far"],
  ["Luce", "Light (illumination)"],
  ["Lumaca", "Snail"],
  ["Luna", "Moon"],
  ["Lungo", "Long"],
  ["Lupo", "Wolf"],
  // --- M ---
  ["Ma", "But"],
  ["Macchina da scrivere", "Typewriter"],
  ["Macchina fotografica", "Camera"],
  ["Maestra", "Teacher"],
  ["Maglietta", "T-shirt"],
  ["Maglione", "Sweater"],
  ["Mago", "Magician"],
  ["Magro", "Thin"],
  ["Mai", "Never"],
  ["Malato", "Unwell"],
  ["Male", "Bad"],
  ["Mamma", "Mummy"],
  ["Mangiare", "To eat"],
  ["Mano", "Hand"],
  ["Mare", "Sea"],
  ["Margherita", "Daisy"],
  ["Marinaio", "Sailor"],
  ["Marmellata", "Jam"],
  ["Marrone", "Brown"],
  ["Martello", "Hammer"],
  ["Matita", "Pencil"],
  ["Mattino", "Morning"],
  ["Medicina", "Medicine"],
  ["Mela", "Apple"],
  ["Mezzanotte", "Midnight"],
  ["Mezzogiorno", "Midday"],
  ["Miele", "Honey"],
  ["Minestra", "Soup"],
  ["Molto", "Very"],
  ["Mondo", "World"],
  ["Montagna", "Mountain"],
  ["Moto", "Motorbike"],
  ["Motocross", "Moto-cross"],
  ["Muro", "Wall"],
  ["Musica", "Music"],
  ["Mutande", "Pants"],
  // --- N ---
  ["Naso", "Nose"],
  ["Nave", "Ship"],
  ["Nebbia", "Fog"],
  ["Negozio", "Shop"],
  ["Nero", "Black"],
  ["Nessuno", "Nobody"],
  ["Neve", "Snow"],
  ["Niente", "Nothing"],
  ["No", "No"],
  ["Nome", "Name"],
  ["Nonna", "Grandmother"],
  ["Nonni", "Grandparents"],
  ["Nonno", "Grandfather"],
  ["Notte", "Night"],
  ["Nuotare", "To swim"],
  ["Nuovo", "New"],
  ["Nuvola", "Cloud"],
  // --- O ---
  ["O", "Or"],
  ["Oca", "Goose"],
  ["Occhiali", "Glasses"],
  ["Occhio", "Eye"],
  ["Oceano", "Ocean"],
  ["Odore", "Smell"],
  ["Oggi", "Today"],
  ["Ombrello", "Umbrella"],
  ["Orecchio", "Ear"],
  ["Oro", "Gold"],
  ["Orologio", "Watch"],
  ["Orso", "Bear"],
  ["Ospedale", "Hospital"],
  // --- P ---
  ["Pagina", "Page"],
  ["Palla", "Ball"],
  ["Pallacanestro", "Basketball"],
  ["Pancia", "Tummy"],
  ["Panda", "Panda"],
  ["Pane", "Bread"],
  ["Pantaloni", "Trousers"],
  ["Papà", "Daddy"],
  ["Pappagallo", "Parrot"],
  ["Paracadute", "Parachute"],
  ["Parco", "Park"],
  ["Parlare", "To speak"],
  ["Partire", "To leave"],
  ["Passaporto", "Passport"],
  ["Patata", "Potato"],
  ["Patatine", "French fries"],
  ["Pattinare", "To skate"],
  ["Paura (avere)", "To be afraid"],
  ["Pecora", "Sheep"],
  ["Penna", "Pen"],
  ["Pensare", "To think"],
  ["Pentola", "Pot"],
  ["Per", "For"],
  ["Per piacere", "Please"],
  ["Pera", "Pear"],
  ["Perché", "Why / Because"],
  ["Perdere", "To lose"],
  ["Pericolo", "Danger"],
  ["Pesante", "Heavy"],
  ["Pesca", "Peach"],
  ["Pescatore", "Fisherman"],
  ["Pettine", "Comb"],
  ["Piacere", "To like"],
  ["Piangere", "To cry"],
  ["Piatto", "Plate"],
  ["Piazza", "Square"],
  ["Piccolo", "Small"],
  ["Piede", "Foot"],
  ["Pieno", "Full"],
  ["Pigiama", "Pyjamas"],
  ["Pigro", "Lazy"],
  ["Pinguino", "Penguin"],
  ["Pioggia", "Rain"],
  ["Pipistrello", "Bat"],
  ["Piramide", "Pyramid"],
  ["Piscina", "Swimming pool"],
  ["Pisello", "Pea"],
  ["Pittore", "Painter"],
  ["Poco", "Little"],
  ["Poi", "Then"],
  ["Poliziotto", "Police officer"],
  ["Poltrona", "Armchair"],
  ["Pomeriggio", "Afternoon"],
  ["Pomodoro", "Tomato"],
  ["Pompelmo", "Grapefruit"],
  ["Pompiere", "Fireman"],
  ["Ponte", "Bridge"],
  ["Porcellino", "Pig"],
  ["Porta", "Door"],
  ["Portare", "To take"],
  ["Porto", "Port"],
  ["Postino", "Postman"],
  ["Potere", "Can"],
  ["Pranzo", "Lunch"],
  ["Prato", "Lawn"],
  ["Premio", "Prize"],
  ["Prendere", "To take"],
  ["Presto", "Early"],
  ["Prima", "Before"],
  ["Primavera", "Spring"],
  ["Prosciutto", "Ham"],
  ["Pulito", "Clean"],
  // --- Q ---
  ["Quaderno", "Notebook"],
  ["Quadrato", "Square"],
  ["Quadrifoglio", "Four-leaf clover"],
  ["Quadro", "Picture"],
  ["Quale", "Which?"],
  ["Quando", "When"],
  ["Quanto", "How much?"],
  ["Quelli", "Those"],
  ["Quello", "That"],
  ["Quercia", "Oak"],
  ["Questi", "These"],
  ["Questo", "This"],
  ["Qui", "Here"],
  ["Quotidiano", "Daily"],
  // --- R ---
  ["Raccontare", "To tell"],
  ["Radio", "Radio"],
  ["Raffreddore", "Cold"],
  ["Ragno", "Spider"],
  ["Ramo", "Branch"],
  ["Ranocchio", "Frog"],
  ["Re", "King"],
  ["Regalo", "Present"],
  ["Regina", "Queen"],
  ["Rettangolo", "Rectangle"],
  ["Ricco", "Rich"],
  ["Ridere", "To laugh"],
  ["Rinoceronte", "Rhinoceros"],
  ["Ripetere", "To repeat"],
  ["Riso", "Rice"],
  ["Risposta", "Answer"],
  ["Ristorante", "Restaurant"],
  ["Robot", "Robot"],
  ["Rosa", "Rose"],
  ["Rosa", "Pink"],
  ["Rosso", "Red"],
  ["Rumore", "Noise"],
  ["Ruota", "Wheel"],
  // --- S ---
  ["Sabbia", "Sand"],
  ["Sale", "Salt"],
  ["Salire", "To go up"],
  ["Salsiccia", "Sausage"],
  ["Saltare", "To jump"],
  ["Sapere", "To know"],
  ["Sapone", "Soap"],
  ["Scala", "Ladder"],
  ["Scarpa", "Shoe"],
  ["Scatola", "Box"],
  ["Scendere", "To go down"],
  ["Sceriffo", "Sheriff"],
  ["Sci", "Ski"],
  ["Scimmia", "Monkey"],
  ["Scoiattolo", "Squirrel"],
  ["Scopa", "Broom"],
  ["Scrivere", "To write"],
  ["Scuola", "School"],
  ["Scusa", "Sorry"],
  ["Se", "If"],
  ["Sedersi", "To sit down"],
  ["Sedia", "Chair"],
  ["Semaforo", "Traffic light"],
  ["Sempre", "Always"],
  ["Sentire", "To hear"],
  ["Senza", "Without"],
  ["Sera", "Evening"],
  ["Serpente", "Snake"],
  ["Sete (avere)", "To be thirsty"],
  ["Sì", "Yes"],
  ["Sinistra", "Left"],
  ["Slitta", "Sleigh"],
  ["Solamente", "Only"],
  ["Soldato", "Soldier"],
  ["Soldi", "Money"],
  ["Sole", "Sun"],
  ["Sopra", "On"],
  ["Sorella", "Sister"],
  ["Sorpresa", "Surprise"],
  ["Sotto", "Under"],
  ["Sottomarino", "Submarine"],
  ["Spada", "Sword"],
  ["Spazzola", "Brush"],
  ["Specchio", "Mirror"],
  ["Spesso", "Often"],
  ["Spiaggia", "Beach"],
  ["Spinaci", "Spinach"],
  ["Spingere", "To push"],
  ["Sporco", "Dirty"],
  ["Sport", "Sport"],
  ["Squalo", "Shark"],
  ["Stanco", "Tired"],
  ["Stazione", "Station"],
  ["Stella", "Star"],
  ["Strada", "Road"],
  ["Strisce pedonali", "Pedestrian crossing"],
  ["Struzzo", "Ostrich"],
  ["Studiare", "To study"],
  ["Su", "Up"],
  ["Suonare", "To play"],
  ["Sveglia", "Alarm clock"],
  ["Svegliarsi", "To wake up"],
  // --- T ---
  ["Tacchino", "Turkey"],
  ["Tagliare", "To cut"],
  ["Tanti", "Many"],
  ["Tanto", "Much"],
  ["Tappeto", "Carpet"],
  ["Tardi", "Late"],
  ["Tartaruga", "Tortoise"],
  ["Tasca", "Pocket"],
  ["Tavolo", "Table"],
  ["Taxi", "Taxi"],
  ["Tazza", "Cup"],
  ["Tè", "Tea"],
  ["Teatro", "Theatre"],
  ["Telefono", "Telephone"],
  ["Televisione", "Television"],
  ["Tesoro", "Treasure"],
  ["Testa", "Head"],
  ["Tetto", "Roof"],
  ["Tigre", "Tiger"],
  ["Tirare", "To pull"],
  ["Topo", "Mouse"],
  ["Torta", "Cake"],
  ["Tovaglia", "Tablecloth"],
  ["Tra", "Between"],
  ["Treno", "Train"],
  ["Triangolo", "Triangle"],
  ["Tromba", "Trumpet"],
  ["Tutto", "All"],
  // --- U ---
  ["Uccello", "Bird"],
  ["Ufficio", "Office"],
  ["Un, Uno, Una", "A / An"],
  ["Uomo", "Man"],
  ["Uovo", "Egg"],
  ["Uva", "Grape"],
  // --- V ---
  ["Vacanza", "Holiday"],
  ["Valigia", "Suitcase"],
  ["Vaso", "Vase"],
  ["Vecchio", "Old"],
  ["Vedere", "To see"],
  ["Vela", "Sail"],
  ["Veloce", "Fast"],
  ["Venire", "To come"],
  ["Vento", "Wind"],
  ["Verde", "Green"],
  ["Verdura", "Vegetables"],
  ["Vestito", "Dress"],
  ["Vetro", "Glass"],
  ["Viaggiare", "To travel"],
  ["Vigile", "Local police officer"],
  ["Vino", "Wine"],
  ["Viola", "Purple"],
  ["Volare", "To fly"],
  ["Volere", "To want"],
  ["Volpe", "Fox"],
  ["Vulcano", "Volcano"],
  // --- Z ---
  ["Zaino", "Rucksack"],
  ["Zanzara", "Mosquito"],
  ["Zattera", "Raft"],
  ["Zucca", "Pumpkin"],
  ["Zucchero", "Sugar"],
];

// HOW TO ADD/EDIT AN "A TO Z" WORD
// ---------------------------------
// 1. Find the "// --- X ---" comment for the correct starting letter
//    (these are just markers for readability -- script.js doesn't read
//    them, it derives the letter list itself from each pair's own first
//    character).
// 2. Add or edit an ["Italian", "English"] entry in that block, keeping
//    it in the same relative order as the source spreadsheet.
// 3. If you add a word whose first letter doesn't appear anywhere else
//    in this file yet (e.g. the first-ever "H" word), no other change is
//    needed -- the az-letter-btn cycle in script.js picks up new letters
//    automatically.
// 4. Bump this file's own "?v=N" in script.js's
//    import { VOCAB_A_TO_Z } from './vocab-a-to-z.js?v=N'; line.
