// verbs-data.js
//
// This file holds ONLY verb vocabulary data — no game logic, no HTML, no
// styling. Safe to edit freely: add new words to an existing list, or add
// a whole new list (see the "HOW TO ADD A NEW LIST" note near the bottom).
//
// Named "verbs-data.js" (rather than "vocab-<name>.js") because it's the
// one exception to the category-file pattern below — verbs aren't a
// vocabulary category. Broad vocabulary categories (Household, and future
// ones like Food & Drink or Transport) live in their own vocab-<name>.js
// files instead — see vocab-household.js for the first example of that
// pattern.
//
// Each list is an array of [Italian, English] pairs.

export const VOCAB_ARE = [
  ["Abbracciare", "To hug"],
  ["Abitare", "To live"],
  ["Accettare", "To accept"],
  ["Affittare", "To rent"],
  ["Affrontare", "To face"],
  ["Aiutare", "To help"],
  ["Amare", "To love"],
  ["Ammirare", "To Admire"],
  ["Appoggiare", "To support"],
  ["Apprezzare", "To appreciate"],
  ["Arrivare", "To arrive"],
  ["Ascoltare", "To listen"],
  ["Aspettare", "To wait"],
  ["Attraversare", "To cross"],
  ["Augurare", "To wish"],
  ["Avanzare", "To advance"],
  ["Avvicinare", "To bring closer"],
  ["Baciare", "To kiss"],
  ["Ballare", "To dance"],
  ["Bastare", "To be enough"],
  ["Bloccare", "To block"],
  ["Brillare", "To sparkle"],
  ["Brontolare", "To grumble"],
  ["Bruciare", "To burn"],
  ["Calcolare", "To calculate"],
  ["Calmare", "To calm"],
  ["Cambiare", "To change"],
  ["Camminare", "To walk"],
  ["Cantare", "To sing"],
  ["Capitare", "To happen"],
  ["Catturare", "To capture"],
  ["Cenare", "To have dinner"],
  ["Cercare", "To look for"],
  ["Chiamare", "To call"],
  ["Colorare", "To colour"],
  ["Combinare", "To combine"],
  ["Cominciare", "To begin"],
  ["Comprare", "To buy"],
  ["Concentrare", "To concentrate"],
  ["Confermare", "To confirm"],
  ["Consegnare", "To deliver"],
  ["Consigliare", "To advise"],
  ["Constrastare", "To tackle"],
  ["Contare", "To count"],
  ["Controllare", "To check"],
  ["Cooperare", "To cooperate"],
  ["Costare", "To cost"],
  ["Cucinare", "To cook"],
  ["Curare", "To take care of"],
  ["Creare", "To create"],
  ["Criticare", "To criticise"],
  ["Danzare", "To dance"],
  ["Dedicare", "To dedicate"],
  ["Desiderare", "To desire"],
  ["Dimenticare", "To forget"],
  ["Dimostrare", "To demonstrate"],
  ["Disegnare", "To draw"],
  ["Disturbare", "To disturb"],
  ["Diventare", "To become"],
  ["Divorziare", "To divorce"],
  ["Domandare", "To ask"],
  ["Dubitare", "To doubt"],
  ["Durare", "To take / To last"],
  ["Educare", "To educate"],
  ["Eliminare", "To eliminate"],
  ["Entrare", "To enter"],
  ["Entusiasmare", "To excite"],
  ["Evitare", "To avoid"],
  ["Firmare", "To sign"],
  ["Fissare", "To fix / To stare"],
  ["Formare", "To form"],
  ["Fotografare", "To photograph"],
  ["Frequentare", "To frequent"],
  ["Fumare", "To smoke"],
  ["Giocare", "To play"],
  ["Girare", "To turn"],
  ["Guadagnare", "To earn"],
  ["Guardare", "To look"],
  ["Guidare", "To drive"],
  ["Immaginare", "To imagine"],
  ["Imparare", "To learn"],
  ["Incontrare", "To meet"],
  ["Incoraggiare", "To encourage"],
  ["Indossare", "To wear"],
  ["Indovinare", "To guess"],
  ["Iniziare", "To start"],
  ["Influenzare", "To influence"],
  ["Insegnare", "To teach"],
  ["Interessare", "To interest"],
  ["Inventare", "To invent"],
  ["Invitare", "To invite"],
  ["Irritare", "To irritate"],
  ["Lasciare", "To leave"],
  ["Lanciare", "To throw"],
  ["Lavare", "To wash"],
  ["Levare", "To remove"],
  ["Lavorare", "To work"],
  ["Liberare", "To free"],
  ["Limitare", "To limit"],
  ["Litigare", "To argue"],
  ["Lottare", "To struggle"],
  ["Mandare", "To send"],
  ["Mangiare", "To eat"],
  ["Manifestare", "To manifest"],
  ["Mescolare", "To mix"],
  ["Migliorare", "To improve"],
  ["Moltiplicare", "To multiply"],
  ["Navigare", "To navigate"],
  ["Nominare", "To appoint"],
  ["Noleggiare", "To rent a car"],
  ["Notare", "To notice"],
  ["Nuotare", "To swim"],
  ["Occupare", "To occupy"],
  ["Odiare", "To hate"],
  ["Oliare", "To oil"],
  ["Organizzare", "To organise"],
  ["Osservare", "To observe"],
  ["Ostacolare", "To obstruct"],
  ["Ottimizzare", "To optimise"],
  ["Pagare", "To pay"],
  ["Paragonare", "To compare"],
  ["Parcheggiare", "To park"],
  ["Pareggiare", "To draw a game"],
  ["Parlare", "To speak"],
  ["Partecipare", "To participate"],
  ["Passare", "To pass"],
  ["Pensare", "To think"],
  ["Perdonare", "To forgive"],
  ["Perfezionare", "To perfect"],
  ["Pianificare", "To plan"],
  ["Portare", "To carry"],
  ["Pranzare", "To have lunch"],
  ["Precipitare", "To plummet"],
  ["Prenotare", "To book"],
  ["Preparare", "To prepare"],
  ["Presentare", "To present"],
  ["Procrastinare", "To procrastinate"],
  ["Progettare", "To design"],
  ["Pronunciare", "To pronounce"],
  ["Protestare", "To protest"],
  ["Provare", "To test"],
  ["Pubblicare", "To publish"],
  ["Punteggiare", "To punctuate"],
  ["Quadrare", "To balance"],
  ["Raccomandare", "To recommend"],
  ["Raccontare", "To recount"],
  ["Realizzare", "To realise"],
  ["Regalare", "To gift"],
  ["Regolare", "To regulate"],
  ["Restare", "To stay"],
  ["Ricordare", "To remember"],
  ["Rifiutare", "To refuse"],
  ["Rigettare", "To reject"],
  ["Rilassare", "To relax"],
  ["Ringraziare", "To thank"],
  ["Ripassare", "To review"],
  ["Riscaldare", "To heat up"],
  ["Risparmiare", "To save money"],
  ["Rispettare", "To respect"],
  ["Ritirare", "To withdraw / To collect"],
  ["Ritornare", "To return"],
  ["Rivelare", "To reveal"],
  ["Rubare", "To steal"],
  ["Salutare", "To greet"],
  ["Saltare", "To jump"],
  ["Salvare", "To save"],
  ["Sbagliare", "To make a mistake"],
  ["Scaricare", "To download"],
  ["Sciare", "To ski"],
  ["Scherzare", "To joke"],
  ["Scomodare", "To inconvenience"],
  ["Sforzare", "To make an effort"],
  ["Segnare", "To score a goal"],
  ["Sgridare", "To scold"],
  ["Sognare", "To dream"],
  ["Sopportare", "To endure"],
  ["Sorpassare", "To overtake"],
  ["Sperare", "To hope"],
  ["Spettare", "To await"],
  ["Spiegare", "To explain"],
  ["Sponsorizzare", "To sponsor"],
  ["Sposare/Sposarsi", "To marry"],
  ["Stampare", "To print"],
  ["Stimolare", "To stimulate"],
  ["Stracciare", "To tear"],
  ["Studiare", "To study"],
  ["Suonare", "To play (an instrument)"],
  ["Superare", "To overcome / to pass"],
  ["Tagliare", "To cut"],
  ["Telefonare", "To phone"],
  ["Tentare", "To attempt"],
  ["Tifare", "To support (a team)"],
  ["Toccare", "To touch"],
  ["Tollerare", "To tolerate"],
  ["Tonificare", "To tone"],
  ["Tornare", "To return"],
  ["Trattare", "To treat / To negotiate"],
  ["Trionfare", "To triumph"],
  ["Trovare", "To find"],
  ["Urlare", "To scream"],
  ["Usare", "To use"],
  ["Vacillare", "To waver"],
  ["Valorizzare", "To enhance / To highlight"],
  ["Variare", "To vary"],
  ["Verificare", "To verify"],
  ["Viaggiare", "To travel"],
  ["Vigilare", "To monitor"],
  ["Violare", "To violate"],
  ["Visitare", "To visit"],
  ["Volare", "To fly"],
  ["Vomitare", "To vomit"],
  ["Zoppicare", "To limp"],
];  // [ [Italian, English], ... ]

export const VOCAB_ERE = [
  ["Abbattere", "To knock down"],
  ["Assistere", "To assist"],
  ["Battere", "To beat"],
  ["Cedere", "To give away"],
  ["Combattere", "To fight"],
  ["Competere", "To compete"],
  ["Consistere", "To consist"],
  ["Credere", "To believe"],
  ["Dibattere", "To debate"],
  ["Eccedere", "To exceed"],
  ["Esistere", "To exist"],
  ["Fremere", "To quiver"],
  ["Gemere", "To groan"],
  ["Godere", "To enjoy"],
  ["Insistere", "To insist"],
  ["Intercedere", "To intercede"],
  ["Precedere", "To precede"],
  ["Premere", "To press"],
  ["Procedere", "To proceed"],
  ["Resistere", "To resist"],
  ["Retrocedere", "To relegate / To retrocede"],
  ["Ricevere", "To receive"],
  ["Ripetere", "To repeat"],
  ["Splendere", "To shine"],
  ["Spremere", "To squeeze"],
  ["Sussistere", "To subsist"],
  ["Temere", "To fear"],
  ["Tessere", "To weave"],
  ["Vendere", "To sell"],
];  // [ [Italian, English], ... ]

export const VOCAB_ERE_IRREGULAR = [
  ["Avere", "To have"],
  ["Bere", "To drink"],
  ["Cogliere", "To pick / To gather"],
  ["Comporre", "To compose"],
  ["Condurre", "To lead / To conduct"],
  ["Conoscere", "To know / To be acquainted with"],
  ["Contenere", "To contain"],
  ["Crescere", "To grow"],
  ["Disporre", "To arrange"],
  ["Distrarre", "To distract"],
  ["Dovere", "To have to / Must"],
  ["Esporre", "To expose"],
  ["Essere", "To be"],
  ["Introdurre", "To introduce"],
  ["Mantenere", "To maintain"],
  ["Muovere", "To move"],
  ["Nascere", "To be born"],
  ["Ottenere", "To obtain"],
  ["Parere", "To seem / To appear"],
  ["Piacere", "To like / To please"],
  ["Porre", "To place / To put"],
  ["Potere", "To be able to / Can"],
  ["Produrre", "To produce"],
  ["Proporre", "To propose"],
  ["Raccogliere", "To collect / To gather"],
  ["Ridurre", "To reduce"],
  ["Rimanere", "To remain / To stay"],
  ["Sapere", "To know"],
  ["Scegliere", "To choose"],
  ["Sedere", "To sit"],
  ["Sostenere", "To support / To sustain"],
  ["Spegnere", "To turn off / To extinguish"],
  ["Supporre", "To suppose"],
  ["Tacere", "To be silent"],
  ["Tenere", "To hold / To keep"],
  ["Togliere", "To remove / To take away"],
  ["Tradurre", "To translate"],
  ["Trarre", "To draw / To pull"],
  ["Valere", "To be worth"],
  ["Volere", "To want"],
];  // [ [Italian, English], ... ]

export const LISTS = {
  are: { label: 'Regular -are verbs', pairs: VOCAB_ARE, footer: 'Regular -are verbs · ' + VOCAB_ARE.length + ' pairs' },
  ere: { label: 'Regular -ere verbs', pairs: VOCAB_ERE, footer: 'Regular -ere verbs · ' + VOCAB_ERE.length + ' pairs' },
  ereIrregular: { label: 'Irregular -ere verbs', pairs: VOCAB_ERE_IRREGULAR, footer: 'Irregular -ere verbs · ' + VOCAB_ERE_IRREGULAR.length + ' pairs' },
};

// ---------------------------------------------------------------------------
// HOW TO ADD A NEW LIST (e.g. a new verb group)
// ---------------------------------------------------------------------------
// 1. Add a new "export const VOCAB_YOURNAME = [...]" array above, following
//    the exact same [ "Italian", "English" ] pair format as the others.
// 2. Add one new line inside LISTS above, giving it a short key (used
//    internally) and a label (shown on screen), e.g.:
//
//    yourKey: { label: 'Your List Name', pairs: VOCAB_YOURNAME,
//               footer: 'Your List Name · ' + VOCAB_YOURNAME.length + ' pairs' },
//
// 3. That's it for the data side. To make it clickable on screen, you'll add
//    one menu button in index.html and one line in script.js — covered
//    separately, since that's layout/logic, not vocab.
//
// NOTE: this file (vocab-data.js) is for verb lists only. A new broad
// vocabulary category (like Household) instead gets its own new
// vocab-<name>.js file, following the pattern set by vocab-household.js.
